# Generated by Django 5.0.3 on 2024-03-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Address', models.CharField(max_length=500)),
                ('Mobileno', models.CharField(max_length=100)),
                ('Bloodgrp', models.CharField(max_length=50)),
            ],
        ),
    ]
